# Generated by Django 5.0.3 on 2024-03-27 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
